[build]
  functions = "netlify/functions"  # Directory where your serverless functions are stored

[[redirects]]
  from = "/api/*"  # Any requests to /api/ will be routed to the serverless functions
  to = "/.netlify/functions/:splat"  # This will map to your function paths
  status = 200  # Return a 200 OK status for successful requests
