[build]
  command = "nuxt build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true

[[functions]]
  directory = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true
